# Exercises 1
Chapter 1 (Don't forget that you should be answering these in an IPython notebook.)

List three different real networks and state the nodes and links for each of them.
Tell us of the network you are personally most interested in. Address the following questions:
What are its nodes and links?
How large is it?
Can be mapped out?
Why do you care about it?
In your view what would be the area where network science could have the biggest impact in the next decade? Explain your answer - and base it on the text in the book.

### 3 different networks
Lan network - nodes are PCs links are cabels

Cities - nodes are towns links are roads

Society - nodes are people, links are relationships

### Most  interested
Probably Cities, its basicly the whole planet so really huge. It can be mapped out. I care because it allowed people to move arround and travel. Well so far I believe that the limits where nearly reached since we all the algorithms for shortest path etc are well known. 


# Excercises 2

## 2.1

1. Can be, 2 vertices with degree 2 and 2verts with degree 3
2. Cant be, since all 4 verts have degree-3
3. Cant be, there are 2 seperated graphs
4. Cant be


## 2.2 Graph Representation 


In [40]:
#creating undirected graph
import networkx as nx
G=nx.Graph()

nodes = range(1,7)
G.add_nodes_from(nodes)
print G.nodes()

edges = [
    (1,2),
    (1,6),
    (1,4),
    (1,3),
    (2,3),
    (2,4),
    (3,6)
]
G.add_edges_from(edges)

print G.edges()

[1, 2, 3, 4, 5, 6]
[(1, 2), (1, 3), (1, 4), (1, 6), (2, 3), (2, 4), (3, 6)]


In [37]:
#creating directed graph
DG = nx.DiGraph()
DG.add_nodes_from(range(1,7))

di_edges = [
    (1,2),
    (6,1),
    (4,1),
    (3,1),
    (2,3),
    (3,2),
    (2,4),
    (6,3)
]
DG.add_edges_from(di_edges)


In [30]:
import scipy as sp
#adjency matrices

#undirected 
A_G = nx.adjacency_matrix(G)
print (A_G.todense())

#directed
A_DG = nx.adjacency_matrix(DG)
print (A_DG.todense())


[[0 1 1 1 0 1]
 [1 0 1 1 0 0]
 [1 1 0 0 0 1]
 [1 1 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]
[[0 1 0 0 0 0]
 [0 0 1 1 0 0]
 [1 1 0 0 0 0]
 [1 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 1 0 0 0]]


In [41]:
#adjaency list

#undirected 
for line in nx.generate_adjlist(G):
    print(line)
    
print _
#directed
for line in nx.generate_adjlist(DG):
    print(line)


1 2 3 4 6
2 3 4
3 6
4
5
6

1 2
2 3 4
3 1 2
4 1
5 1 3
6


In [35]:
#The average clustering coefficient of graph G
print(nx.average_clustering(G))

0.638888888889


If you switch the labels of nodes 5 and 6 in G 
* it would pretty much reamain the same. In matrix the "1" would on 5th row and col. In linked list it changes the 6 to 5 otherwise stays the same. 

What kind of information can you not infer from the link list representation of the network that you can infer from the adjacency matrix?

* both representations are equal

In the (a) network, how many paths (with possible repetition of nodes and links) of length 3 exist starting from node 1 and ending at node 3? And in (b)?

In [64]:
all_paths = nx.all_simple_paths(G, source=1, target=3)

paths_count = 0
for path in all_paths:
    print(path)
    paths_count += 1

print "Number of paths in G is "  + str(paths_count)

all_paths = nx.all_simple_paths(DG, source=1, target=3)

paths_count = 0
for path in all_paths:
    print(path)
    paths_count += 1

print "Number of paths in DG is "  + str(paths_count)


[1, 2, 3]
[1, 3]
[1, 4, 2, 3]
[1, 6, 3]
Number of paths in G is 4
[1, 2, 3]
Number of paths in DG is 1


In [72]:
#Degree, Clustering Coefficient and Components

#Degree
print G.degree()
print DG.degree()

#Clustering

print nx.clustering(G)
#print nx.clustering(DG) is not defined for directed graphs

#Components
for item in nx.connected_components(G):
    print item 

print _
for item in nx.strongly_connected_components(DG):
    print item 




{1: 4, 2: 3, 3: 3, 4: 2, 5: 0, 6: 2}
{1: 4, 2: 4, 3: 4, 4: 2, 5: 2, 6: 0}
{1: 0.5, 2: 0.6666666666666666, 3: 0.6666666666666666, 4: 1.0, 5: 0.0, 6: 1.0}
set([1, 2, 3, 4, 6])
set([5])

set([1, 2, 3, 4])
set([5])
set([6])


Consider an undirected network of size N in which each node has degree k = 1. Which condition does N have to satisfy? What is the degree distribution of this network? How many components does the network have?
* There must be N/2 of E, E - edge
* All nodes a have 1 degree
* It has N/2 components

Consider now a network in which each node has degree k = 2 and clustering coefficient C = 1. How does the network look like? What condition does N satisfy in this case?
* its a triangle
* N must be equal to 3


# 2.5 bipartite graphs

In [74]:
from networkx.algorithms import bipartite

In [75]:
BG = nx.Graph()
BG.add_nodes_from(range(1,7), bipartite=0) # Add the node attribute "bipartite"
BG.add_nodes_from(range(7,12), bipartite=1)

In [76]:
edges = [
    (1,7),
    (2,9),
    (3,7),
    (3,8),
    (3,9),
    (4,9),
    (4,10),
    (5,9),
    (5,11),
    (6,11)
]
BG.add_edges_from(edges)

In [77]:
#adjency matrix
A_BG = nx.adjacency_matrix(BG)
print (A_BG.todense())

[[0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 1]
 [1 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0 0]]


 Why is it a block-diagonal matrix?
 * Because there are no connection inbetween each set of verts

Calculate the average degree of the purple nodes and the average degree of the green nodes in the bipartite network.

In [98]:
import numpy as np

degX,degY=bipartite.degrees(BG,range(1,7))
print degX
print degY

for i in degX:
    print degX[i]
    
average_deg_X = sum(degX.itervalues()) / float(len(range(1,7)))

average_deg_Y = sum(degY.itervalues()) / float(len(range(7,12)))

print str(average_deg_X) + " VS " + str(average_deg_Y) 

{8: 1, 9: 4, 10: 1, 11: 2, 7: 2}
{1: 1, 2: 1, 3: 3, 4: 2, 5: 2, 6: 1}
1
4
1
2
2
1.66666666667 VS 2.0


Calculate the average degree in each of the two network projections. Is it surprising that the values are different from those obtained in point (c)?
* no its not suprising 

What is the maximum number of links Lmax the network can have?
* L_max = 2N

How many links cannot occur compared to a non-bipartite network of size N = N1 + N2 ?

* N1 - 1 + N2 - 1



If N1‹‹N2 , what can you say about the network density, that is the total number of links over the maximum number of links, Lmax?
* stays the same?

Find an expression connecting N1, N2 and the average degree for the two sets in the bipartite network, 〈k1〉 and 〈k2〉.
* s

# Part 3: Plotting degree distributions

In [16]:
import matplotlib.pyplot as plt
import numpy as np
import networkx as nx
import random as rnd
import collections

## Binning real numbers

In [104]:
mu, sigma = 2, 0.125 # mean and standard deviation
s = np.random.normal(mu, sigma, 5000)

In [154]:
count, bins = np.histogram(s, density=True)

print bins
#firstBin = bins[0]
bins = np.delete(bins,1,0)


#What does the numpy.histogram function return? 
#returns counts and bins

[ 1.54218793  1.63660524  1.73102255  1.82543986  1.91985717  2.01427448
  2.10869179  2.20310911  2.29752642  2.39194373  2.48636104]


In [155]:
plt.plot(bins,count)
plt.show()

Explain how you deal with this problem and why
* delete the first value in bins because its the edge value

## Binning integers

In [180]:
s = np.random.poisson(10, 5000)

In [181]:
max_range = max(s)
min_range = min(s)

In [182]:
count = range(min_range,max_range+2)
#count = [count[item] + 1 for item in s]
print count
for item in s:
    count[item] += 1

print count

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[1, 2, 6, 38, 105, 196, 352, 455, 561, 625, 624, 563, 525, 378, 270, 164, 137, 86, 51, 40, 27, 24, 22, 24, 24]


In [183]:
plt.bar(range(min_range,max_range+2),count)
plt.show()

## Binning and plotting degree distributions.

In [29]:
# erdos renyi graph
n = 5000
k = 10
p = k/float((n - 1))# k = p*(n-1)

EG = nx.erdos_renyi_graph(n,p) #generate erdos renyi, what kind of name is that?

list_to_sort = []
for n,d in EG.degree().iteritems(): #exttract degrees into separate list
    list_to_sort.append(d)

sorted_degrees = sorted(list_to_sort)
degreeCount=collections.Counter(sorted_degrees) # counts each degree 

deg, cnt = zip(*degreeCount.items()) # unzip dictionary for plotting

In [37]:
#plotting
fig, ax = plt.subplots()
plt.bar(deg, cnt, width=0.80, color='b')
plt.title("Degree Histogram")
plt.ylabel("Count")
plt.xlabel("Degree")
ax.set_xticks([d + 0.4 for d in deg])
ax.set_xticklabels(deg)

plt.show()

# Part 4: Random networks

Consider an Erdős-Rényi network with N = 3,000 nodes, connected to each other with probability p = 10–3.

In [2]:
N = 3000
p = 0.001

#What is the expected number of links, 〈L〉?
L = (p*N*(N-1)) / float(2)

#In which regime is the network?

#Calculate the probability pc so that the network is at critical point
#means <K> = 1
# 1 = p*(N-1)

p_critical = 1/float((N-1))

#Given the linking probability p = 10–3, calculate the number of nodes Ncr so that the network has only one component.

#For the network in (d), calculate the average degree 〈kcr〉 and the average distance between two randomly chosen nodes 〈d〉.

#Calculate the degree distribution pk of this network (approximate with a Poisson degree distribution).

0.00033344448149383126

In [146]:
n = 200
k = 1.5
p = k/float((n - 1))# k = p*(n-1)

EG = nx.erdos_renyi_graph(n,p) #generate erdos renyi, what kind of name is that?

scc = nx.connected_component_subgraphs(EG)

components = {}

for i, component in enumerate(scc):
    nodes = component.nodes()
    components[len(nodes)] = component # the KEY of dict is the size of SCC
    
max_scc = max(components) #find the biggest index from extracted components

extracted_subgraph = components[max_scc] # the biggest SCC from graph

random_scc_point = rnd.choice(extracted_subgraph.nodes()) #pick the random point from the SCC

In [161]:
#Find all nodes that are precisely 2 steps away from the randomly picked node
two_step_away_nodes = nx.single_source_shortest_path_length(extracted_subgraph,random_scc_point,2)
two_step_away_nodes

exact_two_step_away_nodes = []

for i,node in enumerate(two_step_away_nodes):
    dist = two_step_away_nodes[node] #get distance
    if(dist == 2):
        exact_two_step_away_nodes.append(node)


{65: 1, 36: 2, 40: 2, 134: 1, 72: 1, 81: 2, 52: 0, 21: 2, 23: 2, 117: 2, 95: 2}


In [165]:
pos = nx.random_layout(extracted_subgraph,scale=1)

#draw the whole graph
nx.draw(extracted_subgraph,pos,node_size=100, node_color='yellow')

#draw one random node from the SCC
nx.draw_networkx_nodes(extracted_subgraph,pos,
                       nodelist=[random_scc_point],
                       node_color='r',
                       node_size=500,
                   alpha=0.5)

#draw nodes exact 2 step away from the random picked node
nx.draw_networkx_nodes(extracted_subgraph,pos,
                       nodelist= exact_two_step_away_nodes,
                       node_color='blue',
                       node_size=400,
                   alpha=0.5)



#nx.draw(EG,pos=nx.spring_layout(EG,scale=0.1)) # use spring layout
plt.show()